POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "fullName": "Doessxxxx",
    "email": "john.doe@testixxxxxnddg.com",
    "password": "12334144",
    "membershipType": "Standard",
    "phoneNumber": "+1234567890"
}


### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
 "email": "john.doe@testixxxxxnddg.com",
    "password": "12334144"
}



