### Create a new book
POST http://localhost:8080/roles
Content-Type: application/json

{
    "roleName":"User"
}

### Get roles
GET http://localhost:8080/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJEb2Vzc3h4eHgiLCJpYXQiOjE3Mjg2MTQzNzAsImV4cCI6MTcyODcwMDc3MH0.LsaKujPCXfLIXFdXINR6_wp8uiKhKqt8uYgucTGEZ_E

### Get role by id
GET http://localhost:8080/roles/1

### Delete role by id
DELETE http://localhost:8080/roles/1